on:
  pull_request:
    branches-ignore:
      # ignore this workflow while the develop branch is under heavy construction
      - '**'
jobs:
  check-doc-build:
    name: netCDF-Java Documentation Code Deprecation Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zulu JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          architecture: x64
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Check netCDF-Java documentation for deprecations warnings
        run: './gradlew :docs:testClasses |& (! grep -F "warning: [deprecation]")'
